server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myjwtapp
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect